export const AppContent = {
	brandName: "learner",
	ok: "Ok",
	cancel: "Cancel",
	save: "Save",
	update: "Update",
	close: "Close",
	add: "Add",
	addCourse: "Add course",
	addSection: "Add section",
	editCourse: "Edit course",
	action: "Action",
	delete: "Delete",
	active: "Active",
	inactive: "Inactive",
	edit: "Edit",
};
