export const AppContent = {
	brandName: "learner",
	ok: "Ok",
	cancel: "Cancel",
	save: "Save",
	update: "Update",
	close: "Close",
	add: "Add",
	addCourse: "Add course",
	addSection: "Add section",
	editCourse: "Edit course",
	action: "Action",
	delete: "Delete",
	active: "Active",
	inactive: "Inactive",
	edit: "Edit",
	message: {
		add: "Item added successfully!",
		update: "Item updated successfully!",
		delete: "Item deleted successfully",
		active: "Item activated successfully",
		inactive: "Item inactive successfully",
	},
};
